/* ---------------------------------------------------------------
   STAY_HUB — næsti raunhæfi gististaður (bær) fyrir hvern
   náttúrustað/gönguleið. Notað í "Bóka gistingu í nágrenni"
   hlekkjum svo Booking-leitin skili alvöru niðurstöðum
   (t.d. Goðafoss -> Akureyri, ekki "Goðafoss").
   Sama skrá er lesin af build.py fyrir kyrrstæðu síðurnar.
------------------------------------------------------------------ */
const STAY_HUB = {
  /* Höfuðborgarsvæðið */
  reykjavik: "Reykjavík",
  videy: "Reykjavík",
  grotta: "Reykjavík",
  heidmork: "Reykjavík",
  esjan: "Reykjavík",

  /* Reykjanes */
  brimketill: "Reykjanesbær",
  fagradalsfjall: "Reykjanesbær",
  gardskagi: "Reykjanesbær",
  krysuvik: "Hafnarfjörður",

  /* Vesturland */
  arnarstapi_hellnar: "Arnarstapi",
  glymur: "Akranes",
  grabrok: "Borgarnes",
  hraunfossar: "Húsafell",
  kirkjufell: "Grundarfjörður",
  snaefellsjokull: "Ólafsvík",
  stykkisholmur: "Stykkishólmur",

  /* Vestfirðir */
  dynjandi: "Þingeyri",
  hornstrandir: "Ísafjörður",
  hornvik: "Ísafjörður",
  holmavik: "Hólmavík",
  latrabjarg: "Patreksfjörður",
  isafjordur: "Ísafjörður",

  /* Norðurland vestra */
  blonduos: "Blönduós",
  drangey: "Sauðárkrókur",
  glaumbaer: "Sauðárkrókur",
  hofsos: "Sauðárkrókur",
  hvitserkur: "Hvammstangi",
  kolugljufur: "Hvammstangi",
  kalfshamarsvik: "Skagaströnd",
  skagafjordur: "Sauðárkrókur",
  tindastoll: "Sauðárkrókur",

  /* Norðurland eystra */
  akureyri: "Akureyri",
  aldeyjarfoss: "Akureyri",
  askja: "Mývatn",
  oskjuvegur: "Mývatn",
  dalvik: "Dalvík",
  godafoss: "Akureyri",
  grimsey: "Akureyri",
  arctic_henge: "Húsavík",
  hljodaklettar: "Húsavík",
  hrisey: "Dalvík",
  namaskard: "Mývatn",
  husavik: "Húsavík",
  krafla: "Mývatn",
  laufas: "Akureyri",
  lofthellir: "Mývatn",
  myvatn: "Mývatn",
  siglufjordur: "Siglufjörður",
  sulur: "Akureyri",
  tjornes: "Húsavík",
  vaglaskogur: "Akureyri",
  vindbelgjarfjall: "Mývatn",
  asbyrgi: "Húsavík",
  olafsfjordur: "Ólafsfjörður",

  /* Austurland */
  borgarfjordur_eystri: "Egilsstaðir",
  djupivogur: "Djúpivogur",
  hallormsstadur: "Egilsstaðir",
  hofn: "Höfn",
  seydisfjordur: "Seyðisfjörður",
  stokksnes: "Höfn",
  studlagil: "Egilsstaðir",
  storurd: "Egilsstaðir",
  stodvarfjordur: "Egilsstaðir",

  /* Suðurland */
  fimmvorduhals: "Hvolsvöllur",
  fjadrargljufur: "Kirkjubæjarklaustur",
  geysir: "Laugarvatn",
  gullfoss: "Flúðir",
  jokulsarlon: "Höfn",
  kerid: "Selfoss",
  kerlingarfjoll: "Flúðir",
  landmannalaugar: "Hella",
  laugavegurinn: "Hella",
  reykjadalur: "Hveragerði",
  reynisfjara: "Vík í Mýrdal",
  skaftafell: "Kirkjubæjarklaustur",
  skogafoss: "Hvolsvöllur",
  solheimajokull: "Vík í Mýrdal",
  solheimasandur: "Vík í Mýrdal",
  vestmannaeyjar: "Vestmannaeyjar",
  thingvellir: "Laugarvatn",
  thorsmork: "Hvolsvöllur",
};

if (typeof module !== "undefined") {
  module.exports = { STAY_HUB   "dettifoss": "Mývatn",
  "seljalandsfoss": "Hvolsvöllur",
  "demantsstrondin": "Höfn",
  "husdyragardurinn_reykjavik": "Reykjavík",
  "whales_of_iceland": "Reykjavík",
  "perlan_wonders_of_iceland": "Reykjavík",
  "arbaejarsafn": "Reykjavík",
  "flyover_iceland": "Reykjavík",
  "aurora_reykjavik": "Reykjavík",
  "vikingaheimar": "Keflavík",
  "duus_safnahus": "Keflavík",
  "rokksafn_islands": "Keflavík",
  "landnamssetur_borgarnes": "Borgarnes",
  "haafell_geitfjarsetur": "Borgarnes",
  "erpsstadir_rjomabu": "Búðardalur",
  "slakki-dyragardur": "Selfoss",
  "lava-centre-hvolsvollur": "Hvolsvöllur",
  "efstidalur-ii": "Laugarvatn",
  "icelandic-lava-show-vik": "Vík",
  "eldheimar-vestmannaeyjar": "Vestmannaeyjar",
  "sea-life-trust-beluga-sanctuary": "Vestmannaeyjar",
  "skogasafn-skogar-museum": "Skógar",
  "hestheimar-horse-farm": "Hella",
  "sogusetrid-saga-centre": "Hvolsvöllur",
  "sveitagardurinn-petting-zoo": "Selfoss",
  "selasetur-islands": "Hvammstangi",
  "glaumbaer-torfbaer": "Sauðárkrókur",
  "1238-orrusta-islands": "Sauðárkrókur",
  "brunastadir-dyrabaer": "Siglufjörður",
  "hvalasafnid-husavik": "Húsavík",
  "jolagardurinn-akureyri": "Akureyri",
  "lystigardur-akureyrar": "Akureyri",
  "motorhjolasafn-islands": "Akureyri",
  "daladyrd-dyrabaer": "Akureyri",
  "kjarnaskogur-akureyri": "Akureyri",
  "skrimslasetrid-bildudalur": "Bíldudalur",
  "melrakkasetur-sudavik": "Ísafjörður",
  "galdrasyning-holmavik": "Hólmavík",
  "obyggdasetur-fljotsdalur": "Egilsstaðir",
  "steinasafn-petru-stodvarfjordur": "Stöðvarfjörður",
  "skriduklaustur-fljotsdalur": "Egilsstaðir",
  "osvor-bolungarvik": "Bolungarvík",
  "minjasafn-austurlands-egilsstadir": "Egilsstaðir",
  "samuel-jonsson-selardalur": "Bíldudalur",
  "hrafnseyri-jon-sigurdsson": "Þingeyri",
  "papeyjarferdir-djupivogur": "Djúpivogur",
  "eimverk_distillery": "Garðabær",
  "alafoss_ullarverslun": "Mosfellsbær",
  "handprjonasamband_islands": "Reykjavík",
  "kolaportid_flohamarkadur": "Reykjavík",
  "aegir_brugghus": "Reykjavík",
  "farmers_and_friends": "Reykjavík",
  "burid_islenska_buri": "Reykjavík",
  "duus_handverk": "Keflavík",
  "ullarselid_hvanneyri": "Hvanneyri",
  "brugghus_stedja": "Borgarnes",
  "ljomalind_sveitamarkadur": "Borgarnes",
  "olvisholt-brugghus": "Selfoss",
  "smidjan-brugghus-vik": "Vík",
  "olverk-pizza-brugghus": "Hveragerði",
  "brothers-brewery-vestmannaeyjar": "Vestmannaeyjar",
  "eimverk-floki-distillery": "Hella",
  "skyrgerdin-hveragerdi": "Hveragerði",
  "solheimar-vala-verslun": "Sólheimar (Grímsnes)",
  "vikurprjon-icewear-vik": "Vík",
  "hespuhusid-jurtalitun": "Selfoss",
  "thingborg-ullarvinnsla": "Selfoss",
  "solskinsbudin-fludir": "Flúðir",
  "kidka-hvammstangi": "Hvammstangi",
  "atlantic-leather-saudarkrokur": "Sauðárkrókur",
  "brunastadir-fljot": "Fljót",
  "langafit-laugarbakki": "Laugarbakki",
  "stadarskali-hrutafjordur": "Hrútafjörður",
  "bruggsmidjan-kaldi-arskogssandur": "Árskógssandur",
  "segull-67-siglufjordur": "Siglufjörður",
  "holtsel-eyjafjordur": "Akureyri",
  "kaffi-ku-eyjafjordur": "Akureyri",
  "vogafjos-myvatn": "Mývatn",
  "fjalladyrd-modrudalur": "Möðrudalur",
  "flora-akureyri": "Akureyri",
  "modir-jord-vallanes": "Egilsstadir",
  "beljandi-brugghus": "Breiddalsvik",
  "austri-brugghus-askur": "Egilsstadir",
  "khb-brugghus": "Borgarfjordur eystri",
  "hus-handanna": "Egilsstadir",
  "dokkan-brugghus": "Isafjordur",
  "saltverk-reykjanes": "Isafjordur",
  "simbahollin-thingeyri": "Thingeyri",
  "fisherman-sudureyri": "Sudureyri",
  "ivaf-knitwear": "Isafjordur",
  "kaupfelag-holmavik": "Holmavik",
  "glerarlaug": "Akureyri",
  "bjarnalaug": "Akranes",
  "gvendarlaug_bjarnarfirdi": "Hólmavík",
  "hreppslaug": "Borgarnes",
  "heydalur": "Ísafjörður",
  "illugastadir": "Akureyri",
  "skeidalaug": "Selfoss",
  "solgardar": "Siglufjörður",
  "djupidalur": "Reykhólar",
  "hraunborgir": "Selfoss",
  "heidarbaer": "Selfoss",
  "heidarborg": "Borgarnes",
  "lundur_oxarfirdi": "Húsavík",
};
}
